name: Fetch AQHI data at :15 past the hour

on:
  workflow_dispatch:   # lets you click “Run workflow” in Actions
  schedule:
    - cron: '15 * * * *'  # every hour at 15 minutes past

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Fetch AQHI
        run: npm run fetch

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@DKevinM/datafetch2.noreply.github.com"
          git add datafetch/aqhi_week.json
          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update AQHI snapshot"
          git push
        env:
          # this special token lets Actions push back to your repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
